apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: streaming-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      initContainers:
        - name: setup-keystore
          image: openjdk:11-jre
          command: ["sh", "-c"]
          args:
            - |
              # Echo info for debugging:
              ls -la /etc/certs/*

              # Convert PEM to PKCS12 for keystore
              openssl pkcs12 -export \
                -in /etc/certs/tls.crt \
                -inkey /etc/certs/tls.key \
                -out /tmp/kafka-client.p12 \
                -name kafka-client \
                -password pass:$PASSWORD;

              # Create the keystore
              keytool -importkeystore \
                -deststorepass $PASSWORD \
                -destkeypass $PASSWORD \
                -destkeystore /etc/kafka/secrets/jks/tls.keystore.jks \
                -srckeystore /tmp/kafka-client.p12 \
                -srcstoretype PKCS12 \
                -srcstorepass $PASSWORD \
                -alias kafka-client;

              # Import CA into truststore
              keytool -import \
                -trustcacerts \
                -file /etc/certs/ca.crt \
                -alias ca \
                -keystore /etc/kafka/secrets/jks/tls.truststore.jks \
                -storepass $PASSWORD -noprompt;
          env:
            - name: PASSWORD
              value: "changeit" # Replace with a secure password
          volumeMounts:
            - name: secrets-volume
              mountPath: /etc/kafka/secrets/jks
            - name: client-tls
              mountPath: /etc/certs
      containers:
        - name: producer
          image: confluentinc/cp-kafka:7.4.0
          # command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          command:
            - /bin/bash
            - -c
            - |
              echo "Starting Kafka Producer..."
              kafka-console-producer \
                --broker-list kafka-broker.streaming-pipeline.svc.cluster.local:9093 \
                --producer.config /etc/producer-config/producer.properties \
                --topic demo-topic < /var/producer/producer.demo
          # kafka-console-producer --broker-list kafka-broker.streaming-pipeline.svc.cluster.local:9093 --producer.config /etc/producer-config/producer.properties --topic my-topic
          volumeMounts:
            - name: producer-config
              mountPath: /etc/producer-config
            - name: secrets-volume
              mountPath: /etc/jks
              readOnly: true
            - name: demo-data
              mountPath: /var/producer
      volumes:
        - name: producer-config
          configMap:
            name: producer-config
        - name: client-tls
          secret:
            secretName: producer-tls
        - name: secrets-volume
          emptyDir: {}
        - name: demo-data #TODO. remove when done. Used to validate producer
          configMap:
            name: producer-demo-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: streaming-pipeline
data:
  producer.properties: |
    security.protocol=SSL
    ssl.truststore.location=/etc/jks/tls.truststore.jks
    ssl.truststore.password=changeit
    ssl.keystore.location=/etc/jks/tls.keystore.jks
    ssl.keystore.password=changeit
    ssl.key.password=changeit
    ssl.keystore.type=PKCS12
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-demo-data
  namespace: streaming-pipeline
data:
  producer.demo: |
    First message
    Second message
    And the third message
    Some other message which can be a long string of words that form a long sentence.
    Final message