apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: streaming-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      initContainers:
        - name: setup-keystore
          image: openjdk:11-jre
          command: ["sh", "-c"]
          args:
            - |
              # Echo info for debugging:
              ls -la /etc/certs/*

              # Convert PEM to PKCS12 for keystore
              openssl pkcs12 -export \
                -in /etc/certs/tls.crt \
                -inkey /etc/certs/tls.key \
                -out /tmp/kafka-client.p12 \
                -name kafka-client \
                -password pass:$PASSWORD;

              # Create the keystore
              keytool -importkeystore \
                -deststorepass $PASSWORD \
                -destkeypass $PASSWORD \
                -destkeystore /etc/kafka/secrets/jks/tls.keystore.jks \
                -srckeystore /tmp/kafka-client.p12 \
                -srcstoretype PKCS12 \
                -srcstorepass $PASSWORD \
                -alias kafka-client;

              # Import CA into truststore
              keytool -import \
                -trustcacerts \
                -file /etc/certs/ca.crt \
                -alias ca \
                -keystore /etc/kafka/secrets/jks/tls.truststore.jks \
                -storepass $PASSWORD -noprompt;
          env:
            - name: PASSWORD
              value: "changeit" # Replace with a secure password
          volumeMounts:
            - name: secrets-volume
              mountPath: /etc/kafka/secrets/jks
            - name: client-tls
              mountPath: /etc/certs
      containers:
        - name: consumer
          image: confluentinc/cp-kafka:7.4.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Starting Kafka Consumer..."
              kafka-console-consumer \
                --bootstrap-server kafka-broker.streaming-pipeline.svc.cluster.local:9093 \
                --consumer.config /etc/consumer-config/consumer.properties \
                --topic demo-topic \
                --from-beginning
          volumeMounts:
            - name: consumer-config
              mountPath: /etc/consumer-config
            - name: secrets-volume
              mountPath: /etc/jks
              readOnly: true
      volumes:
        - name: consumer-config
          configMap:
            name: consumer-config
        - name: client-tls
          secret:
            secretName: consumer-tls
        - name: secrets-volume
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: streaming-pipeline
data:
  consumer.properties: |
    security.protocol=SSL
    ssl.truststore.location=/etc/jks/tls.truststore.jks
    ssl.truststore.password=changeit
    ssl.keystore.location=/etc/jks/tls.keystore.jks
    ssl.keystore.password=changeit
    ssl.key.password=changeit
    ssl.keystore.type=PKCS12
