apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: streaming-pipeline
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
  - port: 9092
    name: internal
  - port: 9093
    name: external