apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: streaming-pipeline
data:
  server.properties: |
    broker.id=${KAFKA_BROKER_ID}
    listeners=INTERNAL://:9092,EXTERNAL://:9093
    advertised.listeners=INTERNAL://kafka-${KAFKA_BROKER_ID}.kafka-headless.streaming-pipeline.svc.cluster.local:9092,EXTERNAL://kafka-${KAFKA_BROKER_ID}.kafka-headless.streaming-pipeline.svc.cluster.local:9093
    listener.security.protocol.map=INTERNAL:SSL,EXTERNAL:SSL
    inter.broker.listener.name=INTERNAL
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/var/lib/kafka/data
    num.partitions=3
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    zookeeper.connect=zookeeper-service:2181
    zookeeper.connection.timeout.ms=18000
    group.initial.rebalance.delay.ms=0
    ssl.keystore.location=/opt/kafka/config/certs/keystore.jks
    ssl.keystore.password=keystore-password
    ssl.key.password=key-password
    ssl.truststore.location=/opt/kafka/config/certs/truststore.jks
    ssl.truststore.password=truststore-password
    ssl.client.auth=required