apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: streaming-pipeline
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: internal
    - port: 9093
      name: external
  selector:
    app: kafka