# TODO. Create a jar to run the job
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job
  namespace: streaming-pipeline
spec:
  template:
    spec:
      containers:
      - name: flink-job
        image: flink:latest
        command: ["/bin/sh", "-c", "bin/flink run -c flink.job.MainClass /path/to/job.jar"]
      restartPolicy: Never
