apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: streaming-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:latest
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
        - containerPort: 8081
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: streaming-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:latest
        args: ["taskmanager"]
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: streaming-pipeline
spec:
  selector:
    app: flink
    component: jobmanager
  ports:
  - port: 8081
    targetPort: 8081