## Optional intermediate CA ##
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: intermediate-ca
  namespace: streaming-pipeline
spec:
  ca:
    secretName: root-ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intermediate-ca-cert
  namespace: streaming-pipeline
spec:
  secretName: intermediate-ca-key-pair
  duration: 43800h # 5 years
  renewBefore: 720h # 30 days
  isCA: true
  commonName: intermediate-ca
  issuerRef:
    name: intermediate-ca
    kind: Issuer